### ISSUE TITLE
Retrieve and display Total Space, Space Used, and Space Available for entire Company

### ISSUE THREAD

**Issue by StevenBallardSB** [Brain-Crumbs/SafeDataSpace#4]
In the DBHandler class create a an array that has total space, space used, and space available for each contract. You can do this with a join query.

In the View class, display the array that was created.

**Comment by Brain-Crumbs** [comment]
In the DBHandler class create a an array that has total space, space used, and space available the entire company. 

In the View class, display the array that was created.

**Comment by StevenBallardSB** [comment]
We need to create a static value to show how much data we can hold.
Possibly a long because we need to hold several thousand terabytes

**Comment by StevenBallardSB** [comment]
The method in the DBHandler class will return an array holding 3 longs, each representing Total Space, Space Used, and Space Available. Space is represented by number of bytes.
